# Generated by Django 4.2.30 on 2026-07-18 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mock', '模拟支付（仅开发环境）'), ('alipay', '支付宝（TODO：待接入官方能力）'), ('wechat', '微信支付（TODO：待接入官方能力）')], max_length=20)),
                ('transaction_no', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', '处理中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='commerce.order')),
            ],
            options={
                'verbose_name': '支付流水',
                'verbose_name_plural': '支付流水',
                'ordering': ('-created_at',),
            },
        ),
    ]
