# Generated by Django 4.2.30 on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "处理中"),
                    ("success", "成功"),
                    ("failed", "失败"),
                    ("reconciliation", "待人工对账"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
