# Generated by Django 4.2.30 on 2026-07-23 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_alter_usercoupon_coupon'),
        ('payments', '0002_alter_paymenttransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commerce.order'),
        ),
    ]
