# Generated by Django 4.2.30 on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stock_reserved",
            field=models.BooleanField(default=False, editable=False, verbose_name="已预占库存"),
        ),
    ]
