# Generated by Django 4.2.30 on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_order_stock_reserved"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_reconciliation_required",
            field=models.BooleanField(default=False, editable=False, verbose_name="待支付人工对账"),
        ),
    ]
