# Generated by Django 4.2.30 on 2026-07-18 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='手机号验证时间')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/%Y/%m/', verbose_name='头像')),
                ('bio', models.CharField(blank=True, max_length=160, verbose_name='个人简介')),
                ('marketing_notifications', models.BooleanField(default=True, verbose_name='接收优惠通知')),
                ('order_notifications', models.BooleanField(default=True, verbose_name='接收订单通知')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='PhoneVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='手机号')),
                ('code', models.CharField(max_length=64, verbose_name='验证码摘要')),
                ('purpose', models.CharField(choices=[('register', '手机号注册'), ('login', '手机号登录'), ('bind', '绑定手机号'), ('reset', '重置密码')], max_length=20, verbose_name='用途')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, verbose_name='校验失败次数')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='最后校验时间')),
                ('sent_to_backend', models.BooleanField(default=False, verbose_name='已提交短信通道')),
            ],
            options={
                'verbose_name': '手机验证码',
                'verbose_name_plural': '手机验证码',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone', 'purpose', 'created_at'], name='accounts_ph_phone_10af1c_idx')],
            },
        ),
    ]
