# Generated by Django 4.2.30 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):
    """为手机号换绑增加相互隔离的旧号、新号验证码用途。"""

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneverificationcode",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "手机号注册"),
                    ("login", "手机号登录"),
                    ("bind", "绑定手机号"),
                    ("change_old", "换绑验证当前手机号"),
                    ("change_new", "换绑验证新手机号"),
                    ("reset", "重置密码"),
                ],
                max_length=20,
                verbose_name="用途",
            ),
        ),
    ]
