# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待付款"),
                    ("paid", "待发货"),
                    ("shipped", "待收货"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                    ("refund", "退款/售后"),
                ],
                default="pending",
                max_length=20,
                verbose_name="订单状态",
            ),
        ),
    ]
