# Generated by Django 4.2.30 on 2026-07-07 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0004_add_cancelled_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="手机号",
                    ),
                ),
                (
                    "phone_verified_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="手机号验证时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
            },
        ),
        migrations.CreateModel(
            name="PhoneVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(db_index=True, max_length=20, verbose_name="手机号"),
                ),
                ("code", models.CharField(max_length=6, verbose_name="验证码")),
                (
                    "purpose",
                    models.CharField(
                        choices=[("login", "手机号登录"), ("bind", "绑定手机号")],
                        max_length=20,
                        verbose_name="用途",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="使用时间"),
                ),
                (
                    "sent_to_backend",
                    models.BooleanField(default=False, verbose_name="已提交短信通道"),
                ),
            ],
            options={
                "verbose_name": "手机验证码",
                "verbose_name_plural": "手机验证码",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["phone", "purpose", "created_at"],
                        name="shop_phonev_phone_b3f465_idx",
                    )
                ],
            },
        ),
    ]
