# Generated by Django 4.2.30 on 2026-07-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_userprofile_phoneverificationcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneverificationcode",
            name="purpose",
            field=models.CharField(
                choices=[("register", "手机号注册"), ("login", "手机号登录"), ("bind", "绑定手机号")],
                max_length=20,
                verbose_name="用途",
            ),
        ),
    ]
