# Generated by Django 4.2 on 2026-07-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_alter_phoneverificationcode_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneverificationcode",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="校验失败次数"),
        ),
        migrations.AddField(
            model_name="phoneverificationcode",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最后校验时间"),
        ),
        migrations.AlterField(
            model_name="phoneverificationcode",
            name="code",
            field=models.CharField(max_length=64, verbose_name="验证码摘要"),
        ),
    ]
