# Generated by Django 4.2 on 2026-07-14 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0007_phoneverificationcode_attempt_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=40, unique=True, verbose_name="券码"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="优惠券名称")),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="使用说明"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("fixed", "满减券"), ("percent", "折扣券")],
                        default="fixed",
                        max_length=20,
                        verbose_name="优惠类型",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="优惠值"
                    ),
                ),
                (
                    "minimum_spend",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="最低消费"
                    ),
                ),
                (
                    "total_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="0 表示不限量", verbose_name="发行数量"
                    ),
                ),
                (
                    "claimed_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="已领取数量"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="生效时间"
                    ),
                ),
                ("valid_until", models.DateTimeField(verbose_name="失效时间")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "优惠券",
                "verbose_name_plural": "优惠券",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("mock", "模拟支付（开发测试）"),
                    ("alipay", "支付宝（暂未开放）"),
                    ("wechat", "微信支付（暂未开放）"),
                ],
                default="mock",
                max_length=20,
                verbose_name="支付方式",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_no",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="支付流水号"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="avatars/%Y/%m/", verbose_name="头像"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.CharField(blank=True, max_length=160, verbose_name="个人简介"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="marketing_notifications",
            field=models.BooleanField(default=True, verbose_name="接收优惠通知"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="order_notifications",
            field=models.BooleanField(default=True, verbose_name="接收订单通知"),
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="领取时间"),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="使用时间"),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coupons",
                        to="shop.coupon",
                        verbose_name="优惠券",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户优惠券",
                "verbose_name_plural": "用户优惠券",
                "ordering": ("-claimed_at",),
            },
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_no",
                    models.CharField(max_length=40, unique=True, verbose_name="售后编号"),
                ),
                ("reason", models.CharField(max_length=100, verbose_name="退款原因")),
                ("description", models.TextField(blank=True, verbose_name="问题描述")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="退款金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已同意"),
                            ("completed", "退款完成"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("admin_note", models.TextField(blank=True, verbose_name="后台备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_request",
                        to="shop.order",
                        verbose_name="订单",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "退款/售后",
                "verbose_name_plural": "退款/售后",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("mock", "模拟支付（开发测试）"),
                            ("alipay", "支付宝（暂未开放）"),
                            ("wechat", "微信支付（暂未开放）"),
                        ],
                        max_length=20,
                        verbose_name="支付渠道",
                    ),
                ),
                (
                    "transaction_no",
                    models.CharField(max_length=64, unique=True, verbose_name="渠道流水号"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "处理中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="回调摘要"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="shop.order",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付流水",
                "verbose_name_plural": "支付流水",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("system", "系统"), ("order", "订单"), ("coupon", "优惠券")],
                        default="system",
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "link",
                    models.CharField(blank=True, max_length=255, verbose_name="站内链接"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="已读")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "站内通知",
                "verbose_name_plural": "站内通知",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BrowsingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now=True, verbose_name="浏览时间")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="browsing_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "浏览记录",
                "verbose_name_plural": "浏览记录",
                "ordering": ("-viewed_at",),
            },
        ),
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="shop.usercoupon",
                verbose_name="使用优惠券",
            ),
        ),
        migrations.AddConstraint(
            model_name="usercoupon",
            constraint=models.UniqueConstraint(
                fields=("user", "coupon"), name="unique_user_coupon"
            ),
        ),
        migrations.AddConstraint(
            model_name="browsinghistory",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="unique_user_product_history"
            ),
        ),
    ]
