# Generated by Django 4.2 on 2026-07-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_coupon_order_payment_method_order_payment_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneverificationcode",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "手机号注册"),
                    ("login", "手机号登录"),
                    ("bind", "绑定手机号"),
                    ("reset", "重置密码"),
                ],
                max_length=20,
                verbose_name="用途",
            ),
        ),
    ]
