# Generated by Django 4.2 on 2026-07-14 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_alter_phoneverificationcode_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="refundrequest",
            name="order_status_before",
            field=models.CharField(
                choices=[
                    ("pending", "待付款"),
                    ("paid", "待发货"),
                    ("shipped", "待收货"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                    ("refund", "退款/售后"),
                ],
                default="paid",
                max_length=20,
                verbose_name="申请前订单状态",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="现价",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=100, verbose_name="库存"),
        ),
    ]
