# Generated by Django 4.2.30 on 2026-07-14 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_refundrequest_order_status_before_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="minimum_spend",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="最低消费",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="优惠值",
            ),
        ),
    ]
