# Generated by Django 4.2.30 on 2026-07-18 09:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标名称')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='现价')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='主图')),
                ('stock', models.PositiveIntegerField(default=100, verbose_name='库存')),
                ('sales', models.PositiveIntegerField(default=0, verbose_name='销量')),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3, verbose_name='评分')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='评价数')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('specs', models.TextField(blank=True, verbose_name='参数信息')),
                ('is_hot', models.BooleanField(default=False, verbose_name='热门商品')),
                ('is_new', models.BooleanField(default=False, verbose_name='新品')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='推荐商品')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='匿名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='商品')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品评价',
                'verbose_name_plural': '商品评价',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('jd', '京东清洗数据'), ('manual', '后台手工录入'), ('merchant', '未来商家平台')], max_length=32, verbose_name='来源类型')),
                ('external_id', models.CharField(max_length=128, verbose_name='外部商品 ID')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='来源链接')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='来源元数据')),
                ('first_imported_at', models.DateTimeField(auto_now_add=True, verbose_name='首次导入时间')),
                ('last_imported_at', models.DateTimeField(auto_now=True, verbose_name='最后导入时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='catalog.product', verbose_name='本地商品')),
            ],
            options={
                'verbose_name': '商品来源',
                'verbose_name_plural': '商品来源',
                'ordering': ('-last_imported_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='图片')),
                ('is_main', models.BooleanField(default=False, verbose_name='是否主图')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True, verbose_name='浏览时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '浏览记录',
                'verbose_name_plural': '浏览记录',
                'ordering': ('-viewed_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='productsource',
            constraint=models.UniqueConstraint(fields=('source_type', 'external_id'), name='catalog_source_external_unique'),
        ),
        migrations.AddConstraint(
            model_name='browsinghistory',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='catalog_history_user_product_unique'),
        ),
    ]
