# Generated by Django 4.2.30 on 2026-07-18 10:15

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("4.8"),
                max_digits=3,
                verbose_name="评分",
            ),
        ),
    ]
