# Generated by Django 4.2.30 on 2026-07-18

from django.db import migrations, models


def initialize_category_scope_and_source_stock(apps, schema_editor):
    """Backfill deterministic category scopes and preserve the current sellable stock as source reference."""

    Category = apps.get_model("catalog", "Category")
    Product = apps.get_model("catalog", "Product")

    # ``parent_scope=0`` represents the root.  A loop is intentionally used instead of a
    # database-specific COALESCE expression so MySQL and SQLite migrations behave identically.
    for category in Category.objects.all().only("id", "parent_id"):
        Category.objects.filter(id=category.id).update(parent_scope=category.parent_id or 0)
    # Existing stock was the only known quantity before this migration.  Preserve it as a
    # reference snapshot; future imports update source_stock without overwriting sellable stock.
    for product in Product.objects.filter(source_stock__isnull=True).only("id", "stock"):
        Product.objects.filter(id=product.id).update(source_stock=product.stock)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent_scope",
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name="父级唯一性键"),
        ),
        migrations.AddField(
            model_name="product",
            name="source_stock",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="来源参考库存"),
        ),
        migrations.RunPython(initialize_category_scope_and_source_stock, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name", "parent_scope"),
                name="catalog_category_parent_name_unique",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=100, verbose_name="可售库存"),
        ),
    ]
