# Generated by Django 4.2.30 on 2026-07-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_category_parent_scope_product_source_stock_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ("-is_main", "sort_order", "id"),
                "verbose_name": "商品图片",
                "verbose_name_plural": "商品图片",
            },
        ),
    ]
