"""
Django settings for shoplite project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import importlib.util
import os
from pathlib import Path


"""""优先使用 django-environ 库（功能更强大），如果没安装则自动降级到 Python 原生的 os.environ。这样项目在任何环境下都能正常运行。"""
# 尝试导入 environ
try:
    import environ
except ImportError:
    # 为后面判断做准备
    environ = None

# 回到django根目录，.parent.parent会回到外层
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# 统一从环境变量或 .env 读取配置；未安装 django-environ 时使用标准库回退。
if environ:
    # 注册环境变量的类型和默认值
    env = environ.Env(
        DEBUG=(bool, True),
        ALLOWED_HOSTS=(list, []),
        SHOPLITE_PAYMENT_SECRET=(str, ""),
        ENABLE_MOCK_PAYMENT=(bool, False),
        SMS_PROVIDER=(str, "console"),
        TENCENT_SMS_SECRET_ID=(str, ""),
        TENCENT_SMS_SECRET_KEY=(str, ""),
        TENCENT_SMS_SDK_APP_ID=(str, ""),
        TENCENT_SMS_SIGN_NAME=(str, ""),
        TENCENT_SMS_TEMPLATE_ID=(str, ""),
        TENCENT_SMS_REGION=(str, "ap-guangzhou"),
        WECHAT_LOGIN_MODE=(str, "disabled"),
        USE_REDIS_CACHE=(bool, False),
        PRODUCTION=(bool, False),
        SECURE_SSL_REDIRECT=(bool, True),
        TRUST_PROXY_HEADERS=(bool, False),
    )
    # 读取项目根目录下的 .env 文件，把里面的键值对加载到环境变量中
    environ.Env.read_env(BASE_DIR / ".env")

    # 封装一个统一的取值函数
    def env_value(name, default=None):
        return env(name, default=default)
else:
    # 普通字符串取值，直接调用 os.environ.get()
    def env_value(name, default=None):
        return os.environ.get(name, default)

    # 手动实现布尔转换，识别 1/true/yes/on（不区分大小写）
    def _env_bool(name, default=False):
        value = os.environ.get(name)
        if value is None:
            return default
        return value.lower() in {"1", "true", "yes", "on"}

    # 手动实现列表转换，按逗号分割，去除空白项
    def _env_list(name, default=None):
        value = os.environ.get(name)
        if not value:
            return default or []
        return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Django 的密钥，用于签名 session、CSRF等。生产环境不能用默认值，随机生成密钥python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = env_value(
    "SECRET_KEY",
    default="shoplite-local-development-only-secret-key-change-before-deployment-2026",
)

# SECURITY WARNING: don't run with debug turned on in production!
# 调试模式。开发环境可以是True，生产环境必须是False
DEBUG = env("DEBUG") if environ else _env_bool("DEBUG", True)

# 允许访问这个 Django 服务的域名或 IP，如ALLOWED_HOSTS = ['myshop.com', 'www.myshop.com', '47.98.123.45']
ALLOWED_HOSTS = env("ALLOWED_HOSTS") if environ else _env_list("ALLOWED_HOSTS")
PRODUCTION = env("PRODUCTION") if environ else _env_bool("PRODUCTION", False)
TRUST_PROXY_HEADERS = env("TRUST_PROXY_HEADERS") if environ else _env_bool("TRUST_PROXY_HEADERS", False)
CSRF_TRUSTED_ORIGINS = (
    env.list("CSRF_TRUSTED_ORIGINS", default=[])
    if environ
    else _env_list("CSRF_TRUSTED_ORIGINS")
)


# Application definition

# 安装应用
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 第三方登录库
    'django.contrib.sites',  # 必须添加
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.weixin',  # 注意是 weixin,
    # 'allauth.socialaccount.providers.alipay',
    'shop'
]

# 如果安装了 `simpleui`，后台会使用 SimpleUI，美化 Django Admin 后台
if importlib.util.find_spec("simpleui"):
    INSTALLED_APPS.insert(0, "simpleui")

# 如果是 DEBUG 并安装了 `debug_toolbar`，启用 Django Debug Toolbar，美化 Django Admin 后台，仅调试时使用
if DEBUG and importlib.util.find_spec("debug_toolbar"):
    INSTALLED_APPS.append("debug_toolbar")

# 如果安装了 `django_htmx`，启用 HTMX 支持，实现局部刷新，无需写 JS
if importlib.util.find_spec("django_htmx"):
    INSTALLED_APPS.append("django_htmx")

# 认证后端(登录界面)，Django原生用户名密码(admin)认证，django-allauth 账号认证
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# 邮件发到控制台，不是真发邮件
EMAIL_BACKEND = ("django.core.mail.backends.console.EmailBackend")

# SITE_ID` 是 allauth/sites 框架需要的站点编号
SITE_ID = 1

# 中间件是请求进入视图前、响应返回浏览器前经过的一层层处理
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",         # 安全中间件
    "django.contrib.sessions.middleware.SessionMiddleware",          # Session
    "django.middleware.common.CommonMiddleware",           # 通用请求处理
    "django.middleware.csrf.CsrfViewMiddleware",           # CSRF 防护
    "django.contrib.auth.middleware.AuthenticationMiddleware",          # 用户认证
    "django.contrib.messages.middleware.MessageMiddleware",           # 消息系统
    "django.middleware.clickjacking.XFrameOptionsMiddleware",            # 防点击劫持
    'allauth.account.middleware.AccountMiddleware',   # 添加这一行，allauth 账号中间件
]

# 整个网站的“总路由表”在 shoplite/urls.py 这个文件里
ROOT_URLCONF = "shoplite.urls"

# 判断有没有这些中间件，将这些中间件插入
if DEBUG and importlib.util.find_spec("debug_toolbar"):
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")

if importlib.util.find_spec("whitenoise"):
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

# 把中间件django_htmx插到django.middleware.csrf.CsrfViewMiddleware前面
if importlib.util.find_spec("django_htmx"):
    MIDDLEWARE.insert(MIDDLEWARE.index("django.middleware.csrf.CsrfViewMiddleware"), "django_htmx.middleware.HtmxMiddleware")

TEMPLATES = [
    {
        # 模板引擎用 DjangoTemplates
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # 额外模板目录是 `BASE_DIR / 'templates'`，也就是 `shoplite/templates/`
        "DIRS": [BASE_DIR / 'templates'],
        # APP_DIRS=True` 表示也会自动找各 app 下的 `templates/`
        "APP_DIRS": True,
        # context processors 会给模板注入 `request`、`user`、messages 等常用变量
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# 生产环境 Gunicorn 会通过这个对象启动 Django,如果用 WSGI 方式启动网站，入口对象在 shoplite/wsgi.py 文件里的 application 变量
WSGI_APPLICATION = "shoplite.wsgi.application"

# 项目统一使用 MySQL。连接信息必须放在环境变量或 Git 忽略的 .env 中，
# 避免开发环境误连 SQLite，也避免把数据库密码提交到源码。
if environ:
    DATABASES = {
        "default": env.db(
            "DATABASE_URL",
            default="mysql://root:@127.0.0.1:3306/shoplite",
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ.get("MYSQL_DATABASE", "shoplite"),
            "USER": os.environ.get("MYSQL_USER", "root"),
            "PASSWORD": os.environ.get("MYSQL_PASSWORD", ""),
            "HOST": os.environ.get("MYSQL_HOST", "127.0.0.1"),
            "PORT": os.environ.get("MYSQL_PORT", "3306"),
            "OPTIONS": {"charset": "utf8mb4"},
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# Django 内置的密码强度校验
AUTH_PASSWORD_VALIDATORS = [
    {
        # 不能太像用户名
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        # 不能太短
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        # 不能太常见
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        # 不能全是数字
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

#  调整为中文
LANGUAGE_CODE = 'zh-hans' #'en-us'
TIME_ZONE = 'Asia/Shanghai' #'UTC'

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# 浏览器访问静态资源的 URL 前缀
STATIC_URL = "static/"
# 是开发时额外查找静态文件的位置
STATICFILES_DIRS = [BASE_DIR / "static"]
# STATIC_ROOT` 是 `collectstatic` 收集静态资源的位置
STATIC_ROOT = BASE_DIR / "staticfiles"
#STORAGES` 中如果安装了 Whitenoise，就使用压缩和带 hash 的静态资源存储
STORAGES = {
    # 用户上传的文件
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # 静态文件，css，js，不会去动的文件
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if PRODUCTION and importlib.util.find_spec("whitenoise")
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

# 用户上传的文件会存到这个文件夹
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# 登录后跳转 `/
LOGIN_REDIRECT_URL = "/"
# 退出后跳转 `/accounts/login/
LOGOUT_REDIRECT_URL = "/accounts/login/"

# allauth 登录方式用用户名
ACCOUNT_LOGIN_METHODS = {"username"}
# 注册字段要求用户名和两次密码
ACCOUNT_SIGNUP_FIELDS = ["username*", "password1*", "password2*"]
# 邮箱验证关闭
ACCOUNT_EMAIL_VERIFICATION = "none"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# 所有模型自动生成的主键 id 字段，都用 大整数类型（BIGINT），这样数据量再大也不用担心主键不够用
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# SimpleUI 管理后台使用同源 iframe 加载管理页面。SAMEORIGIN 允许本站后台正常嵌套，
# 同时仍会阻止第三方网站把 ShopLite 页面嵌入 iframe，避免点击劫持。
X_FRAME_OPTIONS = "SAMEORIGIN"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
if PRODUCTION:
    if not os.environ.get("SECRET_KEY"):
        raise RuntimeError("生产环境必须设置 SECRET_KEY")
    if not ALLOWED_HOSTS:
        raise RuntimeError("生产环境必须设置 ALLOWED_HOSTS")
    DEBUG = False
    SECURE_SSL_REDIRECT = env("SECURE_SSL_REDIRECT") if environ else _env_bool("SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = "Lax"
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_REDIRECT_EXEMPT = [r"^health/$"]


# 从.env或系统环境变量里读取支付密钥，本地开发时默认为空（不启用真实支付），生产环境由运维人员设置真实密钥，保证敏感信息不写死在代码里，SHOPLITE_PAYMENT_SECRET 是项目的支付密钥
SHOPLITE_PAYMENT_SECRET = env_value("SHOPLITE_PAYMENT_SECRET", default="")
ENABLE_MOCK_PAYMENT = env("ENABLE_MOCK_PAYMENT") if environ else _env_bool("ENABLE_MOCK_PAYMENT", False)


# 这一整段都是跟短信发送和微信登录相关的配置，同样是从环境变量或.env文件里读取
"""
变量	                    管什么	                默认值	            生产环境要改吗
SMS_PROVIDER	        选短信服务商	            console（不真实发送）	✅ 改成 tencent
TENCENT_SMS_SECRET_ID	腾讯云密钥 ID	            空	                ✅ 填入真实值
TENCENT_SMS_SECRET_KEY	腾讯云密钥 Key            空	                ✅ 填入真实值
TENCENT_SMS_SDK_APP_ID	腾讯云应用 ID	            空	                ✅ 填入真实值
TENCENT_SMS_SIGN_NAME	短信签名（如【ShopLite】）	空	                ✅ 填入审核通过的签名
TENCENT_SMS_TEMPLATE_ID	短信模板 ID	            空	                ✅ 填入审核通过的模板
TENCENT_SMS_REGION	    腾讯云区域	            ap-guangzhou	    一般不用改
WECHAT_LOGIN_MODE	    微信登录模式	            mock（模拟）	        ✅ 改成 real
"""
SMS_PROVIDER = env_value("SMS_PROVIDER", default="console")
TENCENT_SMS_SECRET_ID = env_value("TENCENT_SMS_SECRET_ID", default="")
TENCENT_SMS_SECRET_KEY = env_value("TENCENT_SMS_SECRET_KEY", default="")
TENCENT_SMS_SDK_APP_ID = env_value("TENCENT_SMS_SDK_APP_ID", default="")
TENCENT_SMS_SIGN_NAME = env_value("TENCENT_SMS_SIGN_NAME", default="")
TENCENT_SMS_TEMPLATE_ID = env_value("TENCENT_SMS_TEMPLATE_ID", default="")
TENCENT_SMS_REGION = env_value("TENCENT_SMS_REGION", default="ap-guangzhou")
WECHAT_LOGIN_MODE = env_value("WECHAT_LOGIN_MODE", default="disabled")

if PRODUCTION:
    if SMS_PROVIDER == "console":
        raise RuntimeError("生产环境必须配置真实短信服务，不能使用 console")
    if WECHAT_LOGIN_MODE == "mock":
        raise RuntimeError("生产环境禁止启用模拟微信登录")

"""
变量	              作用	            本地开发	                        生产环境
REDIS_URL	      Redis服务地址	    用默认值redis://127.0.0.1:6379/0	如果改了Redis地址就修改
USE_REDIS_CACHE	  是否用Redis做缓存	False（用本地内存，省事）	        ✅ 建议改为True，提升性能
"""
REDIS_URL = env_value("REDIS_URL", default="redis://127.0.0.1:6379/0")
USE_REDIS_CACHE = env("USE_REDIS_CACHE") if environ else _env_bool("USE_REDIS_CACHE", False)

'''
Python 的三元表达式语法
正常：
if USE_REDIS_CACHE:
    CACHES = {方案A: Redis缓存}
else:
    CACHES = {方案B: 本地内存缓存}
三元：
CACHES = (
    { 方案A: Redis 缓存 }   ← 如果 USE_REDIS_CACHE = True
    else
    { 方案B: 本地内存缓存 } ← 如果 USE_REDIS_CACHE = False
)

'''
CACHES = (
    {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,    # 从环境变量读来的地址
        }
    }
    if USE_REDIS_CACHE
    else {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "shoplite-local-cache",
        }
    }
)

# 这是 Celery（异步任务队列）的配置。Celery用来处理那些不需要用户立即等到结果的后台任务
'''
配置	                      作用
CELERY_BROKER_URL	      任务队列放 Redis 里
CELERY_RESULT_BACKEND	  任务结果存 Redis 里
CELERY_TIMEZONE	          时区设为北京时间
CELERY_BEAT_SCHEDULE	  每5分钟自动取消超过30分钟未支付的订单
'''
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_TIMEZONE = TIME_ZONE
'''
字段	     值	                                            解释
任务名称	 "cancel-expired-pending-orders"	            只是一个标识名，方便管理
task	 "shop.tasks.cancel_expired_pending_orders"	    告诉 Celery 去执行哪个函数，路径是 shop 应用下的 tasks.py 文件里的 cancel_expired_pending_orders 函数
schedule 300.0	                                        每 300 秒（5 分钟）执行一次
args	 (30,)	                                        传给函数的参数，这里是 30，表示"取消超过 30 分钟仍未支付的订单"
'''
# 终端 1：启动 Celery Worker（真正执行任务的人）
# celery -A shoplite worker --loglevel=info
# 终端 2：启动 Celery Beat（定时发任务的闹钟）
# celery -A shoplite beat --loglevel=info
CELERY_BEAT_SCHEDULE = {
    "cancel-expired-pending-orders": {
        "task": "shop.tasks.cancel_expired_pending_orders",
        "schedule": 300.0,
        "args": (30,),
    }
}


# SimpleUI配置
SIMPLEUI_HOME_INFO = False      # 关掉首页的"简易版使用说明"卡片
SIMPLEUI_HOME_QUICK = False     # 关掉首页的"快捷操作"卡片
SIMPLEUI_HOME_PAGE = ''         # 首页不跳转到外部的链接
SIMPLEUI_HOME_TITLE = 'ShopLite管理后台'  # 浏览器标签页上显示的名称
SIMPLEUI_DEFAULT_THEME = 'simpleui.css'  # 使用默认主题
SIMPLEUI_LOGO = ''              # 左上角 logo 不设置图片
# 核心菜单配置
SIMPLEUI_CONFIG = {
    "system_keep": True,    # 保留 Django 自带的系统管理（用户、组等）
    # 这一行决定了左侧导航栏从上到下显示哪些菜单分类，以及它们的前后顺序。把"系统管理"放在最上面，改一下顺序就行
    "menu_display": ["商品中心", "交易中心", "营销中心", "用户服务", "内容评价", "系统管理"],
    "dynamic": False,       # 菜单不会自动更新
    # 每个菜单的具体内容
    "menus": [
        {
            "name": "商品中心",
            "icon": "fas fa-box-open",   # Font Awesome图标，"icon": "fas fa-XXX"是SimpleUI内部集成了这个图标库的写法
            "models": [
                {"name": "分类管理", "icon": "fas fa-sitemap", "url": "shop/category/"},
                {"name": "商品管理", "icon": "fas fa-store", "url": "shop/product/"},
                {"name": "商品图片", "icon": "fas fa-images", "url": "shop/productimage/"},
            ],
        },
        {
            "name": "交易中心",
            "icon": "fas fa-receipt",
            "models": [
                {"name": "订单管理", "icon": "fas fa-file-invoice", "url": "shop/order/"},
                {"name": "订单明细", "icon": "fas fa-list", "url": "shop/orderitem/"},
                {"name": "购物车项", "icon": "fas fa-shopping-cart", "url": "shop/cartitem/"},
                {"name": "支付流水", "icon": "fas fa-credit-card", "url": "shop/paymenttransaction/"},
                {"name": "退款售后", "icon": "fas fa-undo", "url": "shop/refundrequest/"},
            ],
        },
        {
            "name": "营销中心",
            "icon": "fas fa-ticket-alt",
            "models": [
                {"name": "优惠券", "icon": "fas fa-tags", "url": "shop/coupon/"},
                {"name": "用户优惠券", "icon": "fas fa-ticket-alt", "url": "shop/usercoupon/"},
                {"name": "站内通知", "icon": "fas fa-bell", "url": "shop/notification/"},
            ],
        },
        {
            "name": "用户服务",
            "icon": "fas fa-user-cog",
            "models": [
                {"name": "收货地址", "icon": "fas fa-map-marker-alt", "url": "shop/address/"},
                {"name": "商品收藏", "icon": "fas fa-heart", "url": "shop/favorite/"},
                {"name": "浏览记录", "icon": "fas fa-history", "url": "shop/browsinghistory/"},
            ],
        },
        {
            "name": "内容评价",
            "icon": "fas fa-comments",
            "models": [
                {"name": "商品评价", "icon": "fas fa-star", "url": "shop/review/"},
            ],
        },
        {
            "name": "系统管理",
            "icon": "fas fa-shield-alt",
            "models": [
                {"name": "用户", "icon": "fas fa-users", "url": "auth/user/"},
                {"name": "用户组", "icon": "fas fa-user-friends", "url": "auth/group/"},
                {"name": "站点", "icon": "fas fa-globe", "url": "sites/site/"},
                {"name": "邮箱地址", "icon": "fas fa-envelope", "url": "account/emailaddress/"},
                {"name": "社交账号", "icon": "fas fa-link", "url": "socialaccount/socialaccount/"},
            ],
        },
    ],
}
